#!/usr/bin/env bash
# Write a Bash script that displays a list of currently running processes

ps -eH -o user,stime:9,cmd | grep -w bash | awk 'BEGIN {print "USER STARTED COMMAND"} {print $1, $2, $3, $4}'
