#!/usr/bin/env bash
# myscript.sh

# Create the PID file
echo $$ > /var/run/myscript.pid

# Function to handle cleanup and termination
cleanup() {
    echo "Deleting PID file and terminating..."
    rm -f /var/run/myscript.pid
    exit 0
}

# Trap signals
trap 'echo "I hate the kill command";' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap cleanup SIGQUIT SIGTERM

# Main loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done

