#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
# The checker is running on Docker

if grep -q "127.0.0.2 localhost" /etc/hosts; then
	echo "localhost is already set to 127.0.0.2"
else
	sudo sed -i '/127.0.0.1 localhost/c\127.0.0.2 localhost' /etc/hosts
	echo "localhost updated to 127.0.0.2"
fi

if grep -q "8.8.8.8 facebook.com" /etc/hosts; then
	echo "facebook.com is already set to 8.8.8.8"
else
	echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
	echo "facebook.com updated to 8.8.8.8"
fi
